### ISSUE TITLE
Bug: Wrong size on Microsoft TODO

### ISSUE THREAD

**Issue by mcorossigo** [BlackGlory/favicon-detector#1]
Hello @BlackGlory 

The favicon Microsoft TODO (https://todo.microsoft.com) found here https://todo.microsoft.com/favicon.ico shows a size of 26x10, while the real dimensions are 32x32px.

![Schermata 2019-08-01 alle 12 25 21 2](https://user-images.githubusercontent.com/36412793/62286919-0cb83a80-b459-11e9-8740-312fa13969ce.png)

Thanks

**Comment by BlackGlory** [comment]
The current favicon.ico is 100x100, so this issue is no longer available.
(The new size of 100x100 is obtained from the new version under development)
