### ISSUE TITLE
Better user experience

### ISSUE THREAD

**Issue by BlackGlory** [BlackGlory/favicon-detector#12]
- [x] Vertical content overflow should not hide table headers.
- [x] Replace the loading screen with a progress bar at the top of the window.
- [x] The current version of the message box changes the size of the element when displayed, which is a bug.
- [x] New copy behavior: copy both the icon's image and the icon's URL, if it is possible.

**Comment by BlackGlory** [comment]
~Since browsers only support writing specific MIME types (`text/plain`, `text/html`, `image/png`) to the clipboard, features related to copying images cannot be implemented.~
-  ~Add a button that supports copying both the image of the icon and the URL of the web page.~
-  ~Add a button that supports copying both the image of the icon and the URL of the icon.~

**Comment by BlackGlory** [comment]
So I found this: https://developer.chrome.com/blog/web-custom-formats-for-the-async-clipboard-api
Strangely, `navigator.clipboard.write` always says `DOMException: Write permission denied.`, even though the extension has `clipboardWrite` permission, and the `navigator.clipboard.writeText` just works.

I realized that even if it worked correctly, it would require the application to support special MIME types that start with `web `, which is not much different than not supporting it.

**Comment by BlackGlory** [comment]
This is the new behavior, it only write image if the image is a png.
https://github.com/BlackGlory/favicon-detector/blob/b8127ae29377aea2fb104b71c925eabdc20272e9/src/components/icon-table.tsx#L128-L167

**Comment by shoyuf** [comment]
> This is the new behavior, it only write image if the image is a png.
> 
> https://github.com/BlackGlory/favicon-detector/blob/b8127ae29377aea2fb104b71c925eabdc20272e9/src/components/icon-table.tsx#L128-L167



Maybe you need write a note to explain why add this permission to new version, Because Chrome will stop extension when a extension add a new permission

**Comment by BlackGlory** [comment]
@shoyuf This should be the responsibility of the Chromium development team: why was the clipboard write feature allowed in the past before I added this permission.

**Comment by BlackGlory** [comment]
Perhaps I should indeed remove that permission, since the extension really doesn't need it to work.

**Comment by BlackGlory** [comment]
Just removed the `clipboardWrite` permission in v4.1.2.
