### ISSUE TITLE
Feature request: add easy way to open file in new tab

### ISSUE THREAD

**Issue by mcorossigo** [BlackGlory/favicon-detector#3]
Can you add a new column with the address of the favicon, so that clicking on it result in opening a new tab with the image.

It seems to me a little more conventint than having to copy url, creating a new tab, pasting it and clicking go.

Maybe, instead of writing a potentialy long url into the cell you can add the external link icon (like https://www.flaticon.com/free-icon/external-link-symbol_25284).

As an alternative, allowing `ctrl+click` on the image to open it in a new tab would do the job.

Thanks

**Comment by BlackGlory** [comment]
:thinking: I have some doubts about this feature.
Why do we need to open the icon in a new tab, instead of copying or downloading it directly from the right-click menu?

**Comment by dnknn** [comment]
In fact, to open a single favicon, very simple:  ꖅ drag favicon to page or tab-bar.
 

Add `// @icon ` to copy !

> Of course this is not important, this is for lazy people haha...🤦

- ❓ **Why need it :** 
　　　　Because metadata `// @icon ` of [Tampermonkey UserScript](https://chrome.google.com/webstore/detail/dhdgffkkebhmkfjojejmpbldmpobfkfo)


- 💡 **Implementation plan:**

click 👇 (currently exists)
`https://github.githubassets.com/favicons/favicon.svg`

Shift+click 👇
`// @icon https://github.githubassets.com/favicons/favicon.svg`

or other forms to achieve...

**Comment by BlackGlory** [comment]
@dnknn This does not solve my doubts, why do people need to open icons in new tabs? I mean, if you can save icons or copy icons, it doesn't seem to make much sense.

**Comment by dnknn** [comment]
> it doesn't seem to make much sense.

I think about it carefully, what you said is indeed very reasonable, I withdraw what I said, please ignore it!

**Comment by dnknn** [comment]
> it doesn't seem to make much sense.

I think about it carefully, what you said is indeed very reasonable, I withdraw what I said, please ignore it!

In fact, there is an extension dedicated to viewing pictures on the tab page, so I am habitually thinking, you can try `Viewhance`:

https://github.com/deathamns/Viewhance
https://drive.google.com/drive/folders/0Bx8fnUCX4W2IOTdESEFoM3luS1U

**Comment by BlackGlory** [comment]
Viewhance is a great extension, I have never heard of it before! This makes it meaningful to browse icons in the new tab.

And I noticed that Firefox users don't even have a right-click menu item that can open pictures in new tabs.

I think I will provide this feature in the next version.

**Comment by dnknn** [comment]
> Viewhance is a great extension, I have never heard of it before!

But have you heard of [Imagus](https://chrome.google.com/webstore/detail/immpkjjlgappgfkkfieppnmlhakdmaab)?
`Viewhance` was developed by the author of `Imagus`, who is very low-key!

**Comment by dnknn** [comment]
> Viewhance is a great extension, I have never heard of it before!

But have you heard of [Imagus](https://chrome.google.com/webstore/detail/immpkjjlgappgfkkfieppnmlhakdmaab)?
`Viewhance` was developed by the author of `Imagus`, who is very low-key!

`Viewhance` tip for png/svg (Alpha channel):

1. You can enable the mouse wheel in the settings to zoom the picture.
2. You can use `B` key to switch the background of Alpha channel !

**Comment by dnknn** [comment]
> And I noticed that Firefox users don't even have a right-click menu item that can open pictures in new tabs.

I am not using 🦊Firefox, but I think this is universal, you can try the following extension, only a few lines of code, you can change the code yourself!

View This Image
https://chrome.google.com/webstore/detail/poildibeoniaibomedledajlgfbohjda

`// chrome.tabs.update(tab.id, {"url": info.srcUrl}); }`  change to 👇
`chrome.tabs.create({"url": info.srcUrl}); }`

`"title": "🖼open in new tab(&F)",`

**Comment by BlackGlory** [comment]
I found that Firefox 109 already supports opening images in new tabs,
so I guess this feature is not very necessary anymore.
